Feature: Bugs related to loading a file generated by SODS in Excel

  Scenario: Excel crashes because it expects an entry called "styles.xml"
    Given a sheet "A", size 3x3 and random data
    Given an empty Spreadsheet
    When the client appends the sheet contained in World.sheet
    And save the spreadsheet in the memory
    And gets the "styles.xml" entry in the spreadsheet saved in the memory
    And gets the initial tag of the xml entry
    Then the tag is "office:document-styles"
